
import React from 'react';

const HowToUse: React.FC = () => {
  const interpretSchema = [
    { range: "25 - 30", verdict: "Excellent", status: "Production Ready", color: "text-emerald-400" },
    { range: "18 - 24", verdict: "Acceptable", status: "Monitored Deploy", color: "text-indigo-400" },
    { range: "10 - 17", verdict: "Needs Improvement", status: "Rethink Prompting", color: "text-amber-400" },
    { range: "00 - 09", verdict: "Critical Failure", status: "Logic Collapse", color: "text-rose-500" },
  ];

  return (
    <section className="py-40 px-8 bg-[#05070a] border-t border-white/5 relative overflow-hidden">
      <div className="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-indigo-500/5 to-transparent pointer-events-none" />
      
      <div className="max-w-7xl mx-auto space-y-32 relative z-10">
        <div className="max-w-3xl space-y-6">
          <div className="inline-block px-4 py-1 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-black uppercase tracking-[0.3em]">
            Deployment Protocol
          </div>
          <h2 className="text-5xl md:text-7xl font-black text-white tracking-tighter leading-none">
            Platform <br />
            <span className="text-slate-600">Documentation</span>
          </h2>
          <p className="text-xl text-slate-400 leading-relaxed font-medium">
            Axiom Audit is an infrastructure layer designed for AI Engineers, Risk Officers, and Researchers who require deterministic verification of non-deterministic models.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-12">
          {/* Section 1: Inputs */}
          <div className="space-y-8 p-10 bg-white/[0.02] border border-white/5 rounded-[40px] hover:bg-white/[0.04] transition-all group">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-500 font-mono font-bold group-hover:scale-110 transition-transform">
              01
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-black text-white uppercase tracking-tight">Input Requirements</h3>
              <p className="text-sm text-slate-500 leading-relaxed">
                The engine requires two distinct data points per audit session:
              </p>
              <ul className="space-y-4 pt-2">
                <li className="flex items-start space-x-3">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0" />
                  <span className="text-xs text-slate-300 font-mono leading-relaxed"><strong className="text-white">Context Query:</strong> The exact raw prompt provided to the candidate model, including system instructions.</span>
                </li>
                <li className="flex items-start space-x-3">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0" />
                  <span className="text-xs text-slate-300 font-mono leading-relaxed"><strong className="text-white">Candidate Payload:</strong> The unedited string output generated by the LLM under scrutiny.</span>
                </li>
              </ul>
            </div>
          </div>

          {/* Section 2: Analysis */}
          <div className="space-y-8 p-10 bg-white/[0.02] border border-white/5 rounded-[40px] hover:bg-white/[0.04] transition-all group">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-500 font-mono font-bold group-hover:scale-110 transition-transform">
              02
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-black text-white uppercase tracking-tight">Forensic Output</h3>
              <p className="text-sm text-slate-500 leading-relaxed">
                Upon execution, the Axiom Judge-Engine generates a triple-certified audit report consisting of:
              </p>
              <div className="space-y-4 pt-2">
                <div className="p-4 bg-black/40 border border-white/5 rounded-2xl">
                   <h4 className="text-[10px] font-black text-white uppercase tracking-widest mb-1">Quantitative Scorecard</h4>
                   <p className="text-[11px] text-slate-500">6-dimensional scoring across accuracy, logic, and safety rubrics.</p>
                </div>
                <div className="p-4 bg-black/40 border border-white/5 rounded-2xl">
                   <h4 className="text-[10px] font-black text-white uppercase tracking-widest mb-1">Neural Drift Map</h4>
                   <p className="text-[11px] text-slate-500">Visual highlighting of factual anomalies and hallucination vectors.</p>
                </div>
                <div className="p-4 bg-black/40 border border-white/5 rounded-2xl">
                   <h4 className="text-[10px] font-black text-white uppercase tracking-widest mb-1">PDF Audit Ledger</h4>
                   <p className="text-[11px] text-slate-500">Boardroom-ready compliance document for institutional logging.</p>
                </div>
              </div>
            </div>
          </div>

          {/* Section 3: Interpretation */}
          <div className="space-y-8 p-10 bg-white/[0.02] border border-white/5 rounded-[40px] hover:bg-white/[0.04] transition-all group">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-500 font-mono font-bold group-hover:scale-110 transition-transform">
              03
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-black text-white uppercase tracking-tight">Interpreting Scores</h3>
              <p className="text-sm text-slate-500 leading-relaxed">
                Audit verdicts are calculated via a weighted mean of derived ground truths.
              </p>
              <div className="space-y-3 pt-2">
                {interpretSchema.map((row, i) => (
                  <div key={i} className="flex items-center justify-between p-3 bg-black/40 border border-white/5 rounded-xl group/row hover:border-white/10 transition-colors">
                    <span className="text-[10px] font-mono text-slate-500">{row.range}</span>
                    <span className={`text-[10px] font-black uppercase tracking-widest ${row.color}`}>{row.verdict}</span>
                    <span className="text-[9px] font-bold text-slate-700 uppercase italic group-hover/row:text-slate-500 transition-colors">{row.status}</span>
                  </div>
                ))}
              </div>
              <p className="text-[10px] text-slate-600 font-medium italic pt-2">
                *Calibration scores above 25 are generally considered SOC2 / HIPAA compliant for low-scrutiny autonomous tasks.
              </p>
            </div>
          </div>
        </div>

        <div className="p-12 bg-indigo-600/5 border border-indigo-500/10 rounded-[48px] flex flex-col md:flex-row items-center justify-between gap-12 group">
           <div className="space-y-4 max-w-xl">
             <h3 className="text-3xl font-black text-white tracking-tight">Need for Specialization?</h3>
             <p className="text-base text-slate-400 leading-relaxed font-medium">
               Enterprise users can upload proprietary knowledge bases (RAG-Ready) to calibrate the Forensic Judge for industry-specific terminology and legal frameworks.
             </p>
           </div>
           <button className="px-10 py-5 bg-white text-black font-black uppercase tracking-widest text-xs rounded-2xl hover:scale-105 active:scale-95 transition-all shadow-[0_20px_40px_rgba(255,255,255,0.05)] shrink-0">
             Contact Solutions Architect
           </button>
        </div>
      </div>
    </section>
  );
};

export default HowToUse;
